kind: pipeline
name: default

trigger:
  branch:
    - master
    - alpha
    - beta
    - rc
  event:
    - push

steps:
  - name: install
    image: node:current-alpine
    commands:
      - yarn --frozen-lockfile

  - name: lint
    image: node:current-alpine
    depends_on:
      - install
    commands:
      - yarn command lint:check --concurrency 1

  - name: docs
    image: node:current-alpine
    depends_on:
      - install
    commands:
      - yarn docs:toc

  - name: semantic-release
    image: cenk1cenk2/drone-semantic-release
    depends_on:
      - lint
    settings:
      git_method: gh
      add_modules:
        - '@qiwi/multi-semantic-release'
      override: multi-semantic-release
      git_user_email:
        from_secret: github_username
      github_token:
        from_secret: github_token
      npm_token:
        from_secret: npm_token
    when:
      branch:
        - master
        - beta
      event:
        - push

  - name: restore-cache
    image: meltwater/drone-cache
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    depends_on:
      - lint
    settings:
      restore: true
      path_style: true
      endpoint: https://s3.kilic.dev
      bucket: drone-cache
      region: eu-1
      cache_key: '{{ .Repo.Owner }}_{{ .Repo.Name }}_{{ .Commit.Branch }}'
      mount:
        - 'docs/listr2/.nuxt'
        - 'docs/listr2/dist'

  - name: build
    image: node:current-alpine
    depends_on:
      - semantic-release
    commands:
      - yarn command build
      - yarn command generate
      - yarn command copy:dockerfile

  - name: rebuild-cache
    image: meltwater/drone-cache
    depends_on:
      - build
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: aws_access_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: aws_secret_access_key
    settings:
      rebuild: true
      path_style: true
      endpoint: https://s3.kilic.dev
      bucket: drone-cache
      region: eu-1
      cache_key: '{{ .Repo.Owner }}_{{ .Repo.Name }}_{{ .Commit.Branch }}'
      mount:
        - 'docs/listr2/.nuxt'
        - 'docs/listr2/dist'

  - name: publish-docs-listr2
    image: plugins/docker
    working_dir: /drone/src/docs/listr2
    depends_on:
      - build
    settings:
      registry: docker.kilic.dev
      repo: docker.kilic.dev/html-docs-listr2
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      tag:
        - latest
    when:
      event:
        - push
      branch:
        - master

image_pull_secrets:
  - dockerconfigjson
